/*
-----------------------------------------------------------------------------------------
--------------------------- exportFiles.c General Overview: ---------------------------
-----------------------------------------------------------------------------------------
This file handles the generation of the assembler's output files: .ob, .ent, and .ext files.
The .ob file contains the memory image, the .ent file contains entry labels, and the .ext file
contains external labels, if any exist.
-----------------------------------------------------------------------------------------
*/

/**
 * @brief Exports the .ob, .ent, and .ext files generated by the assembler.
 *
 * This function calls other functions responsible for generating the required output files:
 * - The .ob file (memory image)
 * - The .ent file (entry labels, if any exist)
 * - The .ext file (external labels, if any exist)
 */
void exportFiles();

/**
 * @brief Creates the .ob file, which contains the memory image of the assembler's output.
 *
 * This function generates the .ob file by writing the memory image to it.
 * If the file cannot be created, an error is logged.
 */
void createObFile();

/**
 * @brief Creates the .ent file, which contains entry labels, if any exist.
 *
 * This function generates the .ent file by writing the necessary data for entry labels.
 * If there are no entry labels, the file is not created. If the file cannot be created, an error is logged.
 */
void createEntriesFile();

/**
 * @brief Creates the .ext file, which contains external labels, if any exist.
 *
 * This function generates the .ext file by writing the necessary data for external labels.
 * If there are no external labels, the file is not created. If the file cannot be created, an error is logged.
 */
void createExternalsFile();